### PR TITLE
Add post on using giscus

### LINKED ISSUE #73: Add post about giscus to tips and tricks
Thanks for maintaining this site, it's been a great resource while I transition to Distill!

I wrote a post about using giscus (similar to utterances, but uses GitHub Discussions instead of Issues). I hope it can be added.

Blogpost: https://www.joelnitta.com/posts/2021-11-24_using-giscus/

Source: https://github.com/joelnitta/joelnitta-home/blob/main/_posts/2021-11-24_using-giscus/index.Rmd

### PR DESCRIPTION
**Pull request by joelnitta**
Should resolve #73.

I didn't touch `_footer.html` because I assume it should reflect whenever this is actually merged.

One thing I couldn't figure out: it seems that the HTML file for each post in `_posts` is named with the slug, not `index.html`, yet when they get built to `_site` they are named `index.html` (eg: named by slug [here](https://github.com/jhelvy/distillery/tree/main/_posts/2021-08-14-new-additions) but `index.html` [here](https://github.com/jhelvy/distillery/tree/gh-pages/posts/2021-08-14-new-additions)). I tried manually changing mine to the slug, but it wasn't getting built as `index.html` so I left it as `index`.

### CODE REVIEW

**Comment by jhelvy** [comment]
Looking quickly at your post, I think the index thing might have to do with the use of the {refinery} package. I've never used it so I don't really know what it does, but it appears there is a `slug` parameter that might be how page slugs get created? Anyway, I'm not able to build your post on my end as I don't have {refinery} installed, but it looks like the `index.html` file is good, so I'll merge the PR.

**Comment by joelnitta** [comment]
Thanks! I can confirm your hunch is right. Instead of `distill::create_post()`, I create posts using `refinery::use_article_template()`, which I now see automatically uses `index`. 

BTW, {refinery} is a package in early development by @djnavarro that enables reproducible blog posts by the use of {renv}. I think it's pretty great, since it can be a pain to reproduce old blog posts once various packages have been updated.

Actually... {refinery} may be very useful in the particular case of this website! I gather that you are actually re-rendering each post instead of just importing the HTML via `distill::import_post()`. If those posts were created using {refinery}, you should be able to recreate them using the exact same set of packages (at the exact same versions) they were made with.

Also, I think @djnavarro's blog post on {refinery} would be a perfect addition to Tips and Tricks: https://blog.djnavarro.net/posts/2021-09-30_on-blogging-reproducibly/. Consider it nominated 😁

**Comment by jhelvy** [comment]
Yes, that all makes good sense. I haven't used `distill::import_post()` mostly because I want to insert the blockquote at the top crediting the original author, so I have to re-render the post anyway. Also, some posts were from blogdown sites, so I had to convert those to distill. @djnavarro's post is certainly on the list of posts to add!

**Comment by djnavarro** [comment]
I will eventually send a PR for that post, honest! 😁

**Pull request merged**
