### PR TITLE
Added my site

### PR DESCRIPTION
**Pull request by jeweljohnsonj**

### CODE REVIEW

**Comment by jhelvy** [comment]
Welcome!

**Comment by shannonpileggi** [comment]
I like the visitors count on your main page @jeweljohnsonj, nice add!

**Comment by jeweljohnsonj** [comment]
@shannonpileggi  Thanks for the feedback! I have written a [post](https://jeweljohnsonj.github.io/jeweljohnson.github.io/posts/2021-12-18-quality-of-life-modifications-for-your-distill-webistes/) where one can implement it on their webpage.

**Comment by jhelvy** [comment]
Alright, that's another post on the to-do list to add!

**Pull request merged**
