### PR TITLE
add jmbuhr.de

### PR DESCRIPTION
**Pull request by jmbuhr**

### CODE REVIEW

**Comment by jmbuhr** [comment]
My site also has a darkmode depending on the user's preferences. I wonder if I could manually add two screenshots side by side? Or maybe this rather is something for the Tips and Tricks section?

**Comment by jhelvy** [comment]
Oh the dark / light mode is so cool! There were a bunch of conflicts so I just added the site to `sites.csv` and re-built the site myself. It's up now!

The screenshot is taken automatically, and it grabbed the light mode version, but yes it would be great to add a post under tips and tricks for how you implemented that!

I'm also thinking of coming up with a list of "features" and adding them as tags to the showcase so people can more easily filter the sites based on them.

**Comment by jmbuhr** [comment]
Ah, yes. I was afraid that this would happend, sorry! I also built the site locally to test and installed all the dependencies, but I am assuming I used different package versions than you have. Maybe for this type of project, that is not a package, `renv` is more suited than a description file because it records the exact versions of dependencies.

**Comment by jhelvy** [comment]
Yeah I'm actually currently in the process of setting up Github Actions to automatically build and deploy the site so people don't have to do it on their computers. Once that workflow is up, all you'll need to do is edit the `sites.csv` file and commit and that should trigger a build.

**Comment by jmbuhr** [comment]
I had the feeling that you were working in this :D Very cool!

**Comment by jmbuhr** [comment]
I'll go ahead and write a post on my blog about the darkmode, but I am also happy to copy it over the the tips and trick section when you are ready

**Comment by kaijagahm** [comment]
> Oh the dark / light mode is so cool! There were a bunch of conflicts so I just added the site to `sites.csv` and re-built the site myself. It's up now!
> 
> The screenshot is taken automatically, and it grabbed the light mode version, but yes it would be great to add a post under tips and tricks for how you implemented that!
> 
> I'm also thinking of coming up with a list of "features" and adding them as tags to the showcase so people can more easily filter the sites based on them.

Just a note to say I think your idea about tagging sites by "features" is a GREAT idea.

**Pull request closed without merging**
