### PR TITLE
implement "filter by category" in the showcase

### PR DESCRIPTION
**Pull request by etiennebacher**
As discussed in #7, it would be convenient to filter the showcase by category to keep only the examples that interest us, e.g those with darkmode, academic theme...

This PR implements this type of filters, largely building on the [w3schools example](https://www.w3schools.com/howto/howto_js_filter_elements.asp). Here's a list of additions or modifications to the code:

* I added a few categories in the CSV file, one per column with a 1/0 coding if a website has the feature. The number of categories is not limited, as long as it is placed after the first four columns. However, I think the number of categories should be limited to prevent having too many buttons at the top of the showcase (otherwise, it would need another type of selecting tool, e.g a dropdown).

* I rewrote some functions with `htmltools`. This was needed to embed the chunks more easily inside new `div`s, and I think it also makes the code cleaner and shorter (which is why I removed some functions).

There are still two drawbacks to this PR:

* the table of contents disappears. I don't know if it is compatible with having this filtering system, because the part titles (i.e the name of each website) has to be wrapped in a `div`, which (I guess) prevents the use of the ToC.

* the links to the website and its source are now below the title, and not on the right side anymore. Maybe playing with the CSS could fix that.

I tested this PR locally, but maybe you should "fork my fork" to check if it works for you too before merging this one. Also, I only put my website on the categories I created (and the one of Jannik Buhr because I remember the dark mode).

### CODE REVIEW

**Comment by jhelvy** [comment]
Wow, this is awesome! I just ran your fork locally and the build looks pretty good. My quick thoughts on the two issues you pointed out:

- For the toc, I ran into the same issue on my own site. I'm pretty sure all of the headers wrapped in a <div> get excluded from the auto-generated toc, but I'm wondering if we can't just make our own using {htmltools}? When I look at the html of a page with a toc (e.g. my [lab page](https://jhelvy.github.io/lab.html)), there's a <div> for the toc with the class `"d-contents d-contents-float"` then a nav inside that div with a list of the headers. Maybe we can just built it and insert that div manually. Otherwise we could insert the toc in the main div underneath the filter buttons (which again we'd have to manually build, but that might be easier to build if it's just a markdown list). 
- The links should be easy to move around since they have the class `"icon-link"`, so we could modify the `theme.css` to help with that. I think they're fine though just below the site name. 

On my site I added this css to make the icon links look more like buttons: 

```css
.icon-link {
    background-color: var(--color-primary);
    color: var(--color-white);
    padding: 3px 5px 3px 5px;
    margin: 0 2px 0 2px;
    border-radius: 5px; /* Rounded edges */
}

.icon-link:hover {
    background-color: var(--color-secondary);
    color: var(--color-white);
}
```

Last thought is it would be good to add a short statement above the filter buttons on the showcase stating what those buttons do, something like "Select a category to filter the showcase"

Do you think you could give some of these things a try before I merge this? If you're short on time I can merge it and we can work from the main again.

**Comment by etiennebacher** [comment]
Sure, I'll try to work on that this weekend. Otherwise maybe merge this on a development branch rather than on the main? I've never done that before so I don't know if it's something to modify on my side or on yours

**Comment by jhelvy** [comment]
I just made a dev branch, so I think you would just need to do the pull request again but say you're asking to merge it to dev rather than main.

**Comment by etiennebacher** [comment]
Done, I close this one

**Pull request closed without merging**
